### ISSUE TITLE
Same issue as #117

### ISSUE THREAD

**Issue by SH1N081** [henkmollema/Dommel#244] opened 2020-11-20 13:59 UTC
When working with BaseEntity-classes, Dommel caches the declaring type, so properties will be incorrect for any reflected types.

**Comment by henkmollema** [comment] 2021-04-04 12:13
Duplicate of #252

**Closed by henkmollema** 2021-04-04 12:13 UTC

**Comment by coding-yak** [comment] 2021-05-30 21:48
when will this be release to nuget?

**Comment by henkmollema** [comment] 2021-06-02 05:21
@coding-yak I'll be releasing a new versions this week.

**Comment by coding-yak** [comment] 2021-06-02 19:46
sweet, thank you! @henkmollema
